export const symptoms_list = ['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing', 'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity', 'ulcers_on_tongue', 'muscle_wasting', 'vomiting', 'burning_micturition', 'spotting_ urination', 'fatigue', 'weight_gain', 'anxiety', 'cold_hands_and_feets', 'mood_swings', 'weight_loss', 'restlessness', 'lethargy', 'patches_in_throat', 'irregular_sugar_level', 'cough', 'high_fever', 'sunken_eyes', 'breathlessness', 'sweating', 'dehydration', 'indigestion', 'headache', 'yellowish_skin', 'dark_urine', 'nausea', 'loss_of_appetite', 'pain_behind_the_eyes', 'back_pain', 'constipation', 'abdominal_pain', 'diarrhoea', 'mild_fever', 'yellow_urine', 'yellowing_of_eyes', 'acute_liver_failure', 'fluid_overload', 'swelling_of_stomach', 'swelled_lymph_nodes', 'malaise', 'blurred_and_distorted_vision', 'phlegm', 'throat_irritation', 'redness_of_eyes', 'sinus_pressure', 'runny_nose', 'congestion', 'chest_pain', 'weakness_in_limbs', 'fast_heart_rate', 'pain_during_bowel_movements', 'pain_in_anal_region', 'bloody_stool', 'irritation_in_anus', 'neck_pain', 'dizziness', 'cramps', 'bruising', 'obesity', 'swollen_legs', 'swollen_blood_vessels', 'puffy_face_and_eyes', 'enlarged_thyroid', 'brittle_nails', 'swollen_extremeties', 'excessive_hunger', 'extra_marital_contacts', 'drying_and_tingling_lips', 'slurred_speech', 'knee_pain', 'hip_joint_pain', 'muscle_weakness', 'stiff_neck', 'swelling_joints', 'movement_stiffness', 'spinning_movements', 'loss_of_balance', 'unsteadiness', 'weakness_of_one_body_side', 'loss_of_smell', 'bladder_discomfort', 'foul_smell_of urine', 'continuous_feel_of_urine', 'passage_of_gases', 'internal_itching', 'toxic_look_(typhos)', 'depression', 'irritability', 'muscle_pain', 'altered_sensorium', 'red_spots_over_body', 'belly_pain', 'abnormal_menstruation', 'dischromic _patches', 'watering_from_eyes', 'increased_appetite', 'polyuria', 'family_history', 'mucoid_sputum', 'rusty_sputum', 'lack_of_concentration', 'visual_disturbances', 'receiving_blood_transfusion', 'receiving_unsterile_injections', 'coma', 'stomach_bleeding', 'distention_of_abdomen', 'history_of_alcohol_consumption', 'fluid_overload.1', 'blood_in_sputum', 'prominent_veins_on_calf', 'palpitations', 'painful_walking', 'pus_filled_pimples', 'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting', 'small_dents_in_nails', 'inflammatory_nails', 'blister', 'red_sore_around_nose', 'yellow_crust_ooze']



export const HindiToEnglish = new Map([
    ['खुजली', 'itching'],
    ['त्वचा चकताना', 'skin_rash'],
    ['नोडल स्किन इरप्शन्स', 'nodal_skin_eruptions'],
    ['लगातार छींकना', 'continuous_sneezing'],
    ['कंपन', 'shivering'],
    ['शीतलता', 'chills'],
    ['जोड़ों में दर्द', 'joint_pain'],
    ['पेट में दर्द', 'stomach_pain'],
    ['एसिडिटी', 'acidity'],
    ['जीभ पर अल्सर', 'ulcers_on_tongue'],
    ['मांसपेशियों का क्षय', 'muscle_wasting'],
    ['उल्टी', 'vomiting'],
    ['जलने वाला मूत्राशय', 'burning_micturition'],
    ['मूत्राशय में स्पॉटिंग', 'spotting_ urination'],
    ['थकान', 'fatigue'],
    ['वजन में बढ़ोतरी', 'weight_gain'],
    ['चिंता', 'anxiety'],
    ['सर्दी वाले हाथ और पैर', 'cold_hands_and_feets'],
    ['मूड स्विंग्स', 'mood_swings'],
    ['वजन कमी', 'weight_loss'],
    ['बेचैनी', 'restlessness'],
    ['सुस्ती', 'lethargy'],
    ['गले में दाग', 'patches_in_throat'],
    ['अनियमित शुगर स्तर', 'irregular_sugar_level'],
    ['खांसी', 'cough'],
    ['उच्च बुखार', 'high_fever'],
    ['दुखिए हुए आंखें', 'sunken_eyes'],
    ['सांस की कमी', 'breathlessness'],
    ['पसीना', 'sweating'],
    ['डिहाइड्रेशन', 'dehydration'],
    ['अपचन', 'indigestion'],
    ['सिरदर्द', 'headache'],
    ['पीली त्वचा', 'yellowish_skin'],
    ['गहरा मूत्र', 'dark_urine'],
    ['मतली', 'nausea'],
    ['भूख में कमी', 'loss_of_appetite'],
    ['आंखों के पीछे दर्द', 'pain_behind_the_eyes'],
    ['पीठ दर्द', 'back_pain'],
    ['कब्ज', 'constipation'],
    ['पेट में दर्द', 'abdominal_pain'],
    ['दस्त', 'diarrhoea'],
    ['हल्का बुखार', 'mild_fever'],
    ['पीला मूत्र', 'yellow_urine'],
    ['आंखों का पीलापन', 'yellowing_of_eyes'],
    ['एक्यूट लिवर फेल्योर', 'acute_liver_failure'],
    ['फ्लूइड ओवरलोड', 'fluid_overload'],
    ['पेट में सूजन', 'swelling_of_stomach'],
    ['सूजे हुए लाइम्फ नोड्स', 'swelled_lymph_nodes'],
    ['मलेज', 'malaise'],
    ['ब्लर्ड एंड डिस्टॉर्टेड विजन', 'blurred_and_distorted_vision'],
    ['फ्लेग्म', 'phlegm'],
    ['गले की खराश', 'throat_irritation'],
    ['आँसू बहना', 'watering_from_eyes'],
    ['बढ़ी हुई भूख', 'increased_appetite'],
    ['पॉलियूरिया', 'polyuria'],
    ['परिवार का इतिहास', 'family_history'],
    ['म्यूकॉइड स्पटम', 'mucoid_sputum'],
    ['रस्टी स्पटम', 'rusty_sputum'],
    ['ध्यान की कमी', 'lack_of_concentration'],
    ['दृष्टि विघटन', 'visual_disturbances'],
    ['रक्त संबंधित खराब बुँदें प्राप्त करना', 'receiving_blood_transfusion'],
    ['अस्टेराइल इंजेक्शन प्राप्त करना', 'receiving_unsterile_injections'],
    ['कोमा', 'coma'],
    ['पेट से खून बहना', 'stomach_bleeding'],
    ['पेट में फूलन', 'distention_of_abdomen'],
    ['शराब की अधिक अवधारण', 'history_of_alcohol_consumption'],
    ['फ्लूइड ओवरलोड.1', 'fluid_overload.1'],
    ['स्पुटम में रक्त', 'blood_in_sputum'],
    ['बैंडों पर प्रमुख नसें', 'prominent_veins_on_calf'],
    ['दिल की धड़कन', 'palpitations'],
    ['दर्दभरी चलन', 'painful_walking'],
    ['पस भरे मुहासे', 'pus_filled_pimples'],
    ['काले हेड', 'blackheads'],
    ['स्करिंग', 'scurring'],
    ['त्वचा का छिलना', 'skin_peeling'],
    ['सिल्वर जैसे धूल', 'silver_like_dusting'],
    ['नाखूनों में छोटे गड्ढे', 'small_dents_in_nails'],
    ['सूजा हुआ थाइरॉयड', 'enlarged_thyroid'],
    ['कच्चे नाखून', 'brittle_nails'],
    ['सूजी हुईं अंगुलियाँ', 'swollen_extremeties'],
    ['अत्यधिक भूख', 'excessive_hunger'],
    ['अधिकारिक संपर्क', 'extra_marital_contacts'],
    ['होंठ सुखाना और झिल्ली', 'drying_and_tingling_lips'],
    ['स्लर्ड स्पीच', 'slurred_speech'],
    ['घुटने में दर्द', 'knee_pain'],
    ['हिप जॉइंट में दर्द', 'hip_joint_pain'],
    ['मांसपेशियों में कमजोरी', 'muscle_weakness'],
    ['कठिनता से गर्दन', 'stiff_neck'],
    ['सूजे हुए जोड़ों', 'swelling_joints'],
    ['गति कठिनता', 'movement_stiffness'],
    ['स्पिनिंग मूवमेंट्स', 'spinning_movements'],
    ['ताकत में कमी', 'loss_of_balance'],
    ['अस्थिरता', 'unsteadiness'],
    ['एक शरीर की ओर कमजोरी', 'weakness_of_one_body_side'],
    ['गंध खो जाना', 'loss_of_smell'],
    ['ब्लैडर असुखंड', 'bladder_discomfort'],
    ['मूत्र में बदबू', 'foul_smell_of urine'],
    ['मूत्र की लगातार भावना', 'continuous_feel_of_urine'],
    ['गैसों का पारितोषिक', 'passage_of_gases'],
    ['आंतरिक खुजली', 'internal_itching'],
    ['टॉक्सिक लुक (टायफोस)', 'toxic_look_(typhos)'],
    ['डिप्रेशन', 'depression'],
    ['चिढ़ाहट', 'irritability'],
    ['मांसपेशियों में दर्द', 'muscle_pain'],
    ['बदला हुआ संवेदना', 'altered_sensorium'],
    ['शरीर पर लाल तिले', 'red_spots_over_body'],
    ['पेट में दर्द', 'belly_pain'],
    ['असामान्य मासिक धर्म', 'abnormal_menstruation'],
    ['डिसक्रोमिक पैचेस', 'dischromic _patches'],
    ['आंखों से पानी आना', 'watering_from_eyes'],
    ['बढ़ा हुआ भूख', 'increased_appetite'],
    ['पॉलियूरिया', 'polyuria'],
    ['परिवार का इतिहास', 'family_history'],
    ['म्यूकॉइड स्पटम', 'mucoid_sputum'],
    ['रस्टी स्पटम', 'rusty_sputum'],
    ['ध्यान की कमी', 'lack_of_concentration'],
    ['दृष्टि विघटन', 'visual_disturbances'],
    ['रक्त संबंधित खराब बुँदें प्राप्त करना', 'receiving_blood_transfusion'],
    ['अस्टेराइल इंजेक्शन प्राप्त करना', 'receiving_unsterile_injections'],
    ['कोमा', 'coma'],
    ['पेट से खून बहना', 'stomach_bleeding'],
    ['पेट में फूलन', 'distention_of_abdomen'],
    ['शराब की अधिक अवधारण', 'history_of_alcohol_consumption'],
    ['फ्लूइड ओवरलोड.1', 'fluid_overload.1'],
    ['स्पुटम में रक्त', 'blood_in_sputum'],
    ['बैंडों पर प्रमुख नसें', 'prominent_veins_on_calf'],
    ['दिल की धड़कन', 'palpitations'],
    ['दर्दभरी चलन', 'painful_walking']
])



export const symptomsListHindi = ['खुजली', 'त्वचा चकताना', 'नोडल स्किन इरप्शन्स', 'लगातार छींकना', 'कंपन', 'शीतलता', 'जोड़ों में दर्द', 'पेट में दर्द', 'एसिडिटी', 'जीभ पर अल्सर', 'मांसपेशियों का क्षय', 'उल्टी', 'जलता हुआ मूत्राशय', 'मूत्राशय में स्पॉटिंग', 'थकान', 'वजन में वृद्धि', 'चिंता', 'ठंडे हाथ और पैर', 'मूड स्विंग्स', 'वजन कमी', 'बेचैनी', 'सुस्ती', 'गले में दाग', 'अनियमित शुगर स्तर', 'खांसी', 'उच्च बुखार', 'धुआंधार आंखें', 'सांस की कमी', 'पसीना', 'शूषण', 'अजीर्ण', 'सिरदर्द', 'पीली त्वचा', 'गहरा मूत्र', 'मतली', 'भूख की कमी', 'आंखों के पीछे दर्द', 'पीठ दर्द', 'कब्ज', 'पेट में दर्द', 'दस्त', 'हल्का बुखार', 'पीला मूत्र', 'आंखों का पीलापन', 'तेजी से बीमारी का असर', 'तरल परिसंचार', 'पेट में सूजन', 'सूजा हुआ लिम्फ नोड्स', 'अस्वस्थता', 'धुंधली और विकृत दृष्टि', 'कफ', 'गले में खराश', 'आंखों का लालपन', 'साइनस दबाव', 'बहती हुई नाक', 'ठहराव', 'सीने में दर्द', 'अंगों में कमजोरी', 'तेज हृदय दर', 'मल त्याग के दौरान दर्द', 'गुदा क्षेत्र में दर्द', 'रक्तस्रावी स्टूल', 'गुदा में चिढ़ाना', 'गर्दन में दर्द', 'चक्कर', 'कसावट', 'नीला पड़ना', 'मोटापा', 'सूजी हुई टांगें', 'सूजी हुई रक्त वाहिकाएँ', 'फुला हुआ चेहरा और आंखें', 'बढ़ती हुई गरमी', 'कोमा', 'पेट ब्लीडिंग', 'पेट में फूलाव', 'पेट में बढ़ाव', 'एलर्जी', 'आत्मघात', 'मानसिक अस्थिति', 'मानसिक अस्तित्व', 'मानसिक कमजोरी', 'मानसिक बेहाली', 'मानसिक स्वास्थ्य की समस्याएं', 'सामाजिक छलावा', 'विवादित संबंध', 'संतुलन की व्याख्या करें', 'एलर्जी के लक्षण', 'बदलते मौसम के असर', 'वायरस संक्रमण', 'बैक्टीरियल संक्रमण', 'विषाणु संक्रमण', 'परजीवी संक्रमण', 'ब्रेन ट्यूमर', 'हैमरेज', 'एपिलेप्सी', 'माइग्रेन', 'पार्किंसन रोग', 'आल्जाइमर का रोग', 'मल्टीपल स्क्लेरोसिस', 'स्ट्रोक', 'हाइपरटेंशन', 'हृदय रोग', 'डायबिटीज', 'कैंसर', 'हिव/एड्स', 'किडनी रोग', 'लिवर रोग', 'थायरॉयड रोग', 'पैनक्रिएटिटिस', 'गैस्ट्रोएंटराइटिस', 'क्रोन रोग', 'इरिटेबल बाउल सिंड्रोम', 'रेनल फेलियर', 'जोक्क', 'कोलोरेक्टल कैंसर', 'ब्रेस्ट कैंसर', 'प्रोस्टेट कैंसर', 'ओवेरियन कैंसर', 'हाइड्रोसेल', 'इन्फेक्शन', 'ब्लैकहेड्स', 'पिम्पल्स', 'स्किन बढ़ाव', 'पिक्सुल्स', 'केलोइड', 'बर्न', 'स्कैबीज', 'लाइस', 'जॉक इच', 'फंगल इंफेक्शन', 'स्कैबीज', 'विटिलिगो', 'लीकोडर्मा', 'प्सोरायसिस', 'एक्जिमा', 'स्किन कैंसर', 'मेलेनोमा', 'टॉर्न नेल्स', 'इंग्रोइंग नेल्स', 'हैंगनेल्स', 'नेल्स चैंज कलर', 'नेल्स में स्मॉल डेंट्स', 'नेल्स में इनफ्लेमेटरी चेंजेस', 'नेल्स में ब्लिस्टर', 'नेल्स में रेड सोयर आराउंड नोज', 'नेल्स में येलो क्रस्ट ऊज', 'स्विमिंग नेल्स', 'सिल्वर लाइक डस्टिंग', 'स्मॉल डेंट्स इन नेल्स', 'इनफ्लेमेटरी नेल्स', 'ब्लिस्टर', 'चेहरे के चारों ओर लाल दाग', 'नाक से पानी बहना', 'नाक में खुजली', 'नाक में सूजन', 'नाक में खासी', 'सांस में कमी', 'सांस में तेजी', 'सांस की बड़ी रेट', 'सांस में दुर्गंध', 'पेशाब में कठिनाई', 'पेशाब में बदबू', 'पेशाब की योजना', 'गैस की गूंथ', 'आंतरीय खुजली']

// console.log(symptomsList);
